import { ProductFormData } from "@/validators/product-validators";
import { UploadProduct } from "./product-upload";
import { BaseProductProps, Product } from "./product";
import { ProductStatusEnum } from "@/enums";
import { ProductValidation } from "./decorators/validate-product-info";
import { IProduct } from "@/lib/db/models/product.model";

export class ProductFactory {
  static createUploadProduct(product: ProductFormData) {
    return new UploadProduct(product);
  }

  static create(props: BaseProductProps): Product {
    return new Product(props);
  }

  static createProductWithValidationDecorator(data: ProductFormData) {
    const product = this.create({
      ...data,

      // placeholders
      status: ProductStatusEnum.Pending,
      isVerifiedProduct: false,
      isVisible: false,

      // generated later
      slug: "",

      // generated by persistence layer later
      storeId: "",

      createdAt: new Date(),
      updatedAt: new Date(),
    });

    return new ProductValidation(product);
  }

  static fromPersistence(product: IProduct): Product {
    if (!product._id) {
      throw new Error("ProductId Required");
    }
    return new Product({
      ...product,
      _id: product._id.toString(),
      storeId: product.storeId.toString(),
    });
  }
}
