import "../../globals.css";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import { getStoreFromCookie } from "@/lib/helpers/get-store-from-cookie";
import { StoreSidebar } from "@/modules/store/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { redirect } from "next/navigation";

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";
  const store = await getStoreFromCookie();
  if (!store) {
    redirect(`/login`);
  }
  return (
    <SidebarProvider defaultOpen={defaultOpen}>
      <StoreSidebar store={store} />
      <SidebarTrigger />
      <SidebarInset>
        <main>{children}</main>
      </SidebarInset>
    </SidebarProvider>
  );
}
