import { PERMISSIONS, Permission } from "./permissions";

// Define all available roles
export const ROLES = {
  SUPER_ADMIN: "super_admin",
  PRODUCT_ADMIN: "product_admin",
  ORDER_ADMIN: "order_admin",
  STORE_ADMIN: "store_admin",
  FINANCE_ADMIN: "finance_admin",
  AUDIT_ADMIN: "audit_admin",
  USER_ADMIN: "user_admin",
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

// Permissions assigned to each role
export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.PRODUCT_ADMIN]: [
    PERMISSIONS.VIEW_PRODUCTS,
    PERMISSIONS.VERIFY_PRODUCT,
    PERMISSIONS.UNVERIFY_PRODUCT,
    PERMISSIONS.REJECT_PRODUCT,
    PERMISSIONS.UNPUBLISH_PRODUCT,
  ],

  [ROLES.ORDER_ADMIN]: [
    PERMISSIONS.VIEW_ORDERS,
    PERMISSIONS.UPDATE_ORDER,
    PERMISSIONS.CANCEL_ORDER,
  ],

  [ROLES.STORE_ADMIN]: [
    PERMISSIONS.VIEW_STORES,
    PERMISSIONS.VERIFY_STORE,
    PERMISSIONS.SUSPEND_STORE,
    PERMISSIONS.REJECT_STORE,
  ],

  [ROLES.FINANCE_ADMIN]: [
    PERMISSIONS.VIEW_ESCROW,
    PERMISSIONS.VIEW_WITHDRAWALS,
    PERMISSIONS.VIEW_REFUNDS,
    PERMISSIONS.PROCESS_ESCROW,
  ],

  [ROLES.AUDIT_ADMIN]: [PERMISSIONS.VIEW_AUDIT_LOGS],

  [ROLES.USER_ADMIN]: [
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VERIFY_USER,
    PERMISSIONS.SUSPEND_USER,
  ],
};
