import { AuthUserDecorator } from "./decorators/auth-user.decorator";
import { ProfileUserDecorator } from "./decorators/profile-user-decorator";
import { BaseUser, User } from "./user";
import {
  AuthUserContext,
  IUserInfo,
  ProfileUserContext,
  SignupUserContext,
} from "./user-interface";

export class UserFactory {
  /**
   * Creates a user specifically for the sign‑up flow.
   *
   * This method initialises a full `User` instance with all the registration data
   * provided by the client (name, email, phone, address, etc.) and wraps it with
   * the `AuthUserDecorator`. The resulting object has authentication capabilities:
   * password hashing, password validation, and future security features.
   *
   * Unlike `createAuthUser`, this method **does not** overwrite the address,
   * city, state, or postal code fields with empty strings – it preserves the
   * values passed in, making it suitable for use in your `/api/auth/sign-up` endpoint.
   *
   * @param props - The sign‑up user properties (firstName, lastName, email, password,
   *                phoneNumber, address, cityOfResidence, stateOfResidence, postalCode,
   *                and optionally isVerified).
   * @returns An `AuthUserDecorator` instance that contains all user data and
   *          authentication methods.
   */
  static createSignupUser(props: SignupUserContext): AuthUserDecorator {
    // Ensure isVerified defaults to false if not provided
    const userProps: BaseUser = {
      ...props,
      isVerified: props.isVerified ?? false,
      // System fields: they will be generated by the database or set later
      _id: undefined, // let the database generate it
      createdAt: new Date(), // will be overwritten by the repository if needed
      updatedAt: new Date(),
      followingStores: [], // default empty array
    };

    const baseUser = new User(userProps);
    return new AuthUserDecorator(baseUser);
  }

  /**
   * Creates a base User object.
   * Useful for internal data processing.
   */
  static createBaseUser(props: BaseUser): User {
    return new User(props);
  }

  /**
   * Creates a user decorated with Authentication capabilities.
   * Use this for login, registration, and security checks.
   */
  static createAuthUser(props: AuthUserContext): AuthUserDecorator {
    const baseUser = new User({
      ...props,
      _id: props._id,
      address: "",
      cityOfResidence: "",
      stateOfResidence: "",
      postalCode: "",
      followingStores: [],
      phoneNumber: "",
      createdAt: new Date(),
      updatedAt: new Date(),
      isVerified: false,
    });
    return new AuthUserDecorator(baseUser);
  }

  /**
   * Creates a user decorated for Profile/UI views.
   * Use this for dashboard screens and public profiles.
   */
  static createProfileUser(
    userProps: ProfileUserContext,
  ): ProfileUserDecorator {
    const baseUser = new User({
      ...userProps,
      _id: userProps._id,
      createdAt: new Date(),
      updatedAt: new Date(),
      password: "",
      followingStores: [],
    });
    return new ProfileUserDecorator(baseUser);
  }

  /**
   * Creates a "Full" User that has both Auth and Profile features.
   */
  static createFullUser(props: BaseUser): IUserInfo {
    let user: IUserInfo = new User(props);
    user = new ProfileUserDecorator(user);
    user = new AuthUserDecorator(user);
    return user;
  }
}
