import { StoreHeader } from "@/components/layout/store/nav";
import "../globals.css";
import type { Metadata } from "next";
import { Fragment } from "react";

// Metadata for the application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <StoreHeader />
      {children}
    </Fragment>
  );
}
