// import type { Metadata } from "next";
import "../globals.css";
import { AdminLayout } from "@/modules/admin/AdminLayout";
import { getAdminFromCookie } from "@/lib/helpers/get-admin-from-cookie";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }; // Admin pages don't have specific metadata

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const admin = await getAdminFromCookie();
  return <AdminLayout admin={admin!}>{children}</AdminLayout>; // Non-null assertion operator is used here because we assume the admin will always be present in this layout since I have authentication middleware in place
}
