import type { Metadata } from "next";
import "../globals.css";
import { HomeFooter } from "@/components/layout/home/home-footer";
import { HomeHeader } from "@/components/layout/home/home-nav";
import { Fragment } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Fragment>
      <HomeHeader />
      {children}
      <HomeFooter />
    </Fragment>
  );
}
